#pragma once
// Auto-generated by fit_ff_from_csv.py
// PWM = a*|ticks_per_frame| + b (per side & direction), use sign(target) to apply direction.

struct FFParams {
  float a_pos; // +direction slope (PWM per tick/frame)
  float b_pos; // +direction intercept/deadband (PWM)
  float a_neg; // -direction slope
  float b_neg; // -direction intercept
};

static constexpr FFParams FF_LEFT  = {
  5.207021f, 3.113f,
  4.915355f, 6.126f
};

static constexpr FFParams FF_RIGHT = {
  4.643577f, 6.572f,
  4.874523f, 4.603f
};
